---
title: vocab
---

### 3.1-3.2

- Variable: An abstraction inside a program that can hold a value
- list: a sequence of several variables grouped together
- variable: a way of storing information in a computer program, which could later be changed, referenced, and used
- data types: a set of values and operations on those values
- abstract data types: a data type whose internal representation is hidden from the client
- client: a program that uses a data type
- objects: a structure that can take on a data-type value
- Applications programming interface (API): which is a list of constructors and instance methods or operations, used to specify the behavior of an abstract data type


### 3.3-3.4

- algorithm: finite set of instructions that accomplish a specific task, composed of sequencing, selection, and iteration.
- selection: a section of code is run only if a condition is met.
- iteration: repeating steps or instructions over and over again
- sequencing: outline or set of steps that we do and follow in order that they are given
- variable: you can store an actual value, the value of a variable in another variable, the result of an operation, or result of a procedural call
- String: a sequence of characters

### 3.5-3.7

- Boolean: binary variable with only two possible values, "true" or "false"
- Logical operators allow for boolean values to be evaluated. 
- Algorithm: Finite set of instructions that accomplish a specific task
- Flowchart: We can use flowcharts to help organize the process of conditional statements.
- Nested conditional: A conditional inside of a conditional

### 3.8 and 3.10

- Iteration: Repitition of a Process
- For Loop: FOR LOOP repeats a function for a set number of times; I is the number of times repeated
- While Loop: The while loop is used to repeat a section of code an unknown number of times until a specific condition is met
- Initialization: What sets the counter variable to a starting value. For example (var i = 0) represents an initial value of 0.
- Condition: Allows the computer to know whether or not to keep repeating the loop.
- increment/decrement: Modifies the counter variable after each repetition.
- Indexing / List Index: The position of an element in a list, starting from 0
append, remove, pop: Various methods, append adds an element to the end, remove removes at an index, and pop removes the last item.
- Elements [in a list]: An item in a list.
- Nesting: Having one data type or function inside another data type or function, such as lists or loops.
- array: Another name for a list, depends on the language

### 3.9 and 3.11

- Iteration: Repeating steps, or instructions over and over again. ( this could be also often called a loop )
- Selection: is a decision or question. At some point in an algorithm there may need to be a question because the algorithm has reached a step where one or more options are available.
- Algorithm: A process or set of rules to be followed in calculations or other problem solving operations, especially by a computer.
- Sequential Search: takes longer because each value in a list needs to be checked
- Binary Search: A lot more efficient and it will take the middle value and keep going out until the right answer is checked.
- 